version: '3.9'
 
services:
  mysql:
    image: mysql:latest
    container_name: wordpress-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork
 
  redis:
    image: redis:latest
    container_name: wordpress-redis
    networks:
      - mynetwork
 
  wordpress:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CACHE_HOST: redis
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - mynetwork
    deploy:
      replicas: 2
 
  nginx:
    image: nginx:latest
    container_name: wordpress-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - wordpress
    networks:
      - mynetwork
 
networks:
  mynetwork:
    driver: bridge
 
volumes:
  mysql_data:
  wordpress_data: